/*
Author: Emily "Quinn" McNamee
File Name: script.js for index.html
Date: 1/28/2026
Purpose: To explain comments
*/

// Question-and-answer form
var name = prompt("What is your name?");
console.log("Hello, " + name + "! :>");

// Three favorite websites
console.log("My three favorite websites are:")
console.log("Youtube, Archive of Our Own, and Discord")

// Three favorite games
console.log("My three favorite games are:")
console.log("Hades, Crusader Kings 3, and WarFrame")

// Three favorite artists
console.log("My three favorite artists are:")
console.log("• Jorge Rivera-Herrans, as he composed EPIC: The Musical - a modern retelling of Homer's The Odyssey in a musical medium")
console.log("• bbn0$ - for not only does he make really good modern hip hop, but he also frequently commissions artists to animate to his songs; cultivating an incredibly artistically inspired community")
console.log("• Hayao Miyazaki - the artist, filmmaker, and co-founder of Studio Ghibli. I grew up on the whimsy of those films, as did my siblings. Very fond memories are centered around my family watching Howl's Moving Castle and Spirited Away together.")

//Console will say "Button was clicked!" upon clicking the 'Click Me!' Button
  console.log("Page loaded");
  const button = document.querySelector("button");

  button.addEventListener("click", function () {
    console.log("there was a button click, but you were too far away to hear it");
  });

//Event Listener generated by ChatGPT and re-modified by me so that the parallax scrolling works as intended

const checkerboard = document.getElementById("checkerboard");

window.addEventListener("scroll", () => {
  const scrollY = window.scrollY;
  checkerboard.style.backgroundPosition = `0 ${scrollY * 0.4}px`;
});

