/*
Author: Emily "Quinn" McNamee
File Name: script.js for index.html
Date: 2/5/2026
Purpose: To explain comments
*/

//Event Listener generated by ChatGPT and re-modified by me so that the parallax scrolling works as intended

const checkerboard = document.getElementById("checkerboard");

window.addEventListener("scroll", () => {
  const scrollY = window.scrollY;
  checkerboard.style.backgroundPosition = `0 ${scrollY * 0.4}px`;
});

